### PR TITLE
Added FOSSASAT-2 GFSK recording

### PR DESCRIPTION
**Pull request by jgromes**
Hi,

I added a recording of a couple FOSSASAT-2 GFSK packets - thought it might be useful to have as a reference for SX126x GFSK. The packets decode, though the actual values are mostly nonsense, as the packets were transmitted from a partially gutted engineering model.

### CODE REVIEW

**Comment by daniestevez** [comment]
Thanks!

I had a look at the `.wav` file and it is very saturated. Just take a look at it with Audacity. Is it possible to get a recording that is not saturated? If not, I'll just merge this, but I think a clean recording would be best.

Also, a few (2 or 3 seconds) of recording surrounding one or two packets is generally more than enough, in the interest of a small file size. Otherwise this repository would grow very large.

**Comment by jgromes** [comment]
No problem, I should be able to get a better recording.

**Comment by daniestevez** [comment]
The recording is clipped even if you divide the amplitude by 2:

fossa2_clipped

The amplitude information has been lost without possibility of recovery.

If possible, doing a new recording would be better.

**Comment by jgromes** [comment]
Turns out one of the blocks in my GNURadio chain had a x10 gain (when it was supposed to have 1) - sorry about that, still kinda new to this.

**Comment by daniestevez** [comment]
Thanks! Now that's a good recording. I have manually squashed and merged your commits.

**Pull request closed without merging**
